import axios from "../axios/instance.js";
import endPoints from "./endpoints.js";
export const getUserData = () => axios.get(endPoints.GET_USER_DETAILS);
export const loginUser = (data) => axios.post(endPoints.LOGIN_USER, data);
export const refreshUser = () => axios.post(endPoints.REFRESH_USER);
export const magicLink = (data) => axios.post(endPoints.MAGIC_LINK, data);
export const sendOtp = (data) => axios.post(endPoints.GET_OTP, data);
export const verifyOTP = (data) => axios.post(endPoints.VERIFY_OTP, data);
export const logoutUser = () => axios.post(endPoints.LOGOUT_USER);
export const sendChangePasswordMail = () => axios.post(endPoints.SEND_RESET_PASSWORD_EMAIL);
console.log(endPoints.SEND_RESET_PASSWORD_EMAIL);
