export const myMeetings = [
  {
    title: "Team Meet",
    description: "Weekly Team Meeting",
    date: "Aug 15",
    time: "3:00PM",
    duration: "1 hour",
    Place: "Starbucks, 5th Avenue",
    people: ["Virat Kholi", "Salman Khan"],
    status: "Confirmed",
  },
  {
    title: "Team Meet",
    description: "Weekly Team Meeting",
    date: "Aug 24",
    time: "6:00AM",
    duration: "1 hour",
    Place: "Starbucks, 5th Avenue",
    people: [
      "Virat Kholi",
      "Salman Khan",
      "Dhoni Bhai",
      "Some One",
      "Some Thing",
      "Kushal Deep",
    ],
    status: "Confirmed",
  },
  {
    title: "Project Review",
    description: "Discuss ongoing sprint",
    date: "Aug 15",
    time: "3:00PM",
    duration: "2 hours",
    Place: "Zoom",
    people: ["Virat Kholi", "Salman Khan", "Dhoni Bhai"],
    status: "Pending",
  },

  {
    title: "Client Call",
    description: "Monthly update with client",
    date: "Monday",
    time: "9:00 AM",
    duration: "45 mins",
    Place: "Microsoft Teams",
    people: ["Virat Kholi", "Salman Khan"],
    status: "Confirmed",
  },
];
