# name: CI/CD Pipeline - Vercel Deployment

# on:
#   push:
#     branches: [ main, Dev ]
#   pull_request:
#     branches: [ Dev ]

# jobs:
#   # Job 1: Build and Lint
#   build-and-lint:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20.x'
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci

#     - name: Run ESLint
#       run: npm run lint

#     - name: Build application
#       run: npm run build
#       env:
#         CI: true

#     - name: Check build output
#       run: |
#         echo "Build completed successfully!"
#         echo "Build size:"
#         du -sh dist/
#         ls -la dist/

#   # Job 2: Deploy to Vercel Preview (for PRs to Dev and Dev branch pushes)
#   deploy-preview:
#     runs-on: ubuntu-latest
#     needs: build-and-lint
#     if: github.event_name == 'pull_request' || github.ref == 'refs/heads/Dev'

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Deploy to Vercel (Preview)
#       uses: amondnet/vercel-action@v25
#       id: vercel-preview
#       with:
#         vercel-token: ${{ secrets.VERCEL_TOKEN }}
#         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#         working-directory: ./
#         scope: ${{ secrets.VERCEL_ORG_ID }}

#     - name: Comment Preview URL
#       if: github.event_name == 'pull_request'
#       uses: actions/github-script@v7
#       with:
#         script: |
#           github.rest.issues.createComment({
#             issue_number: context.issue.number,
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#             body: `🚀 **Preview Deployment Ready!**

#             **Preview URL:** ${{ steps.vercel-preview.outputs.preview-url }}

#             Built with commit: ${context.sha.substring(0, 7)}

#             ---
#             *This comment was automatically generated by the CI/CD pipeline*`
#           })

#   # Job 3: Deploy to Vercel Production (main branch only)
#   deploy-production:
#     runs-on: ubuntu-latest
#     needs: build-and-lint
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     environment: production

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Deploy to Vercel (Production)
#       uses: amondnet/vercel-action@v25
#       id: vercel-production
#       with:
#         vercel-token: ${{ secrets.VERCEL_TOKEN }}
#         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#         vercel-args: '--prod'
#         working-directory: ./
#         scope: ${{ secrets.VERCEL_ORG_ID }}

#     - name: Production Deployment Success
#       run: |
#         echo "🎉 Production deployment successful!"
#         echo "Production URL: ${{ steps.vercel-production.outputs.preview-url }}"
